name: EssentialsHomesImporter
main: JackMD\EssentialsHomesImporter\EssentialsHomesImporter
api: [3.0.0, 4.0.0]
version: 1.0.0
author: JackMD
depend: ["EasyHomes"]

commands:
  import:
    description: Start importing all EssentialsPE homes to EasyHomes.